// ============================================================
//  Japanese Flip Cards — Data
// ============================================================

const HIRAGANA = [
  { char: 'あ', romaji: ['a'] },  { char: 'い', romaji: ['i'] },
  { char: 'う', romaji: ['u'] },  { char: 'え', romaji: ['e'] },
  { char: 'お', romaji: ['o'] },
  { char: 'か', romaji: ['ka'] }, { char: 'き', romaji: ['ki'] },
  { char: 'く', romaji: ['ku'] }, { char: 'け', romaji: ['ke'] },
  { char: 'こ', romaji: ['ko'] },
  { char: 'さ', romaji: ['sa'] }, { char: 'し', romaji: ['shi','si'] },
  { char: 'す', romaji: ['su'] }, { char: 'せ', romaji: ['se'] },
  { char: 'そ', romaji: ['so'] },
  { char: 'た', romaji: ['ta'] }, { char: 'ち', romaji: ['chi','ti'] },
  { char: 'つ', romaji: ['tsu','tu'] }, { char: 'て', romaji: ['te'] },
  { char: 'と', romaji: ['to'] },
  { char: 'な', romaji: ['na'] }, { char: 'に', romaji: ['ni'] },
  { char: 'ぬ', romaji: ['nu'] }, { char: 'ね', romaji: ['ne'] },
  { char: 'の', romaji: ['no'] },
  { char: 'は', romaji: ['ha'] }, { char: 'ひ', romaji: ['hi'] },
  { char: 'ふ', romaji: ['fu','hu'] }, { char: 'へ', romaji: ['he'] },
  { char: 'ほ', romaji: ['ho'] },
  { char: 'ま', romaji: ['ma'] }, { char: 'み', romaji: ['mi'] },
  { char: 'む', romaji: ['mu'] }, { char: 'め', romaji: ['me'] },
  { char: 'も', romaji: ['mo'] },
  { char: 'や', romaji: ['ya'] }, { char: 'ゆ', romaji: ['yu'] },
  { char: 'よ', romaji: ['yo'] },
  { char: 'ら', romaji: ['ra'] }, { char: 'り', romaji: ['ri'] },
  { char: 'る', romaji: ['ru'] }, { char: 'れ', romaji: ['re'] },
  { char: 'ろ', romaji: ['ro'] },
  { char: 'わ', romaji: ['wa'] }, { char: 'を', romaji: ['wo','o'] },
  { char: 'ん', romaji: ['n','nn'] },
  // Dakuten
  { char: 'が', romaji: ['ga'] }, { char: 'ぎ', romaji: ['gi'] },
  { char: 'ぐ', romaji: ['gu'] }, { char: 'げ', romaji: ['ge'] },
  { char: 'ご', romaji: ['go'] },
  { char: 'ざ', romaji: ['za'] }, { char: 'じ', romaji: ['ji','zi'] },
  { char: 'ず', romaji: ['zu'] }, { char: 'ぜ', romaji: ['ze'] },
  { char: 'ぞ', romaji: ['zo'] },
  { char: 'だ', romaji: ['da'] }, { char: 'ぢ', romaji: ['ji','di','zi'] },
  { char: 'づ', romaji: ['zu','du'] }, { char: 'で', romaji: ['de'] },
  { char: 'ど', romaji: ['do'] },
  { char: 'ば', romaji: ['ba'] }, { char: 'び', romaji: ['bi'] },
  { char: 'ぶ', romaji: ['bu'] }, { char: 'べ', romaji: ['be'] },
  { char: 'ぼ', romaji: ['bo'] },
  // Handakuten
  { char: 'ぱ', romaji: ['pa'] }, { char: 'ぴ', romaji: ['pi'] },
  { char: 'ぷ', romaji: ['pu'] }, { char: 'ぺ', romaji: ['pe'] },
  { char: 'ぽ', romaji: ['po'] },
];

const KATAKANA = [
  { char: 'ア', romaji: ['a'] },  { char: 'イ', romaji: ['i'] },
  { char: 'ウ', romaji: ['u'] },  { char: 'エ', romaji: ['e'] },
  { char: 'オ', romaji: ['o'] },
  { char: 'カ', romaji: ['ka'] }, { char: 'キ', romaji: ['ki'] },
  { char: 'ク', romaji: ['ku'] }, { char: 'ケ', romaji: ['ke'] },
  { char: 'コ', romaji: ['ko'] },
  { char: 'サ', romaji: ['sa'] }, { char: 'シ', romaji: ['shi','si'] },
  { char: 'ス', romaji: ['su'] }, { char: 'セ', romaji: ['se'] },
  { char: 'ソ', romaji: ['so'] },
  { char: 'タ', romaji: ['ta'] }, { char: 'チ', romaji: ['chi','ti'] },
  { char: 'ツ', romaji: ['tsu','tu'] }, { char: 'テ', romaji: ['te'] },
  { char: 'ト', romaji: ['to'] },
  { char: 'ナ', romaji: ['na'] }, { char: 'ニ', romaji: ['ni'] },
  { char: 'ヌ', romaji: ['nu'] }, { char: 'ネ', romaji: ['ne'] },
  { char: 'ノ', romaji: ['no'] },
  { char: 'ハ', romaji: ['ha'] }, { char: 'ヒ', romaji: ['hi'] },
  { char: 'フ', romaji: ['fu','hu'] }, { char: 'ヘ', romaji: ['he'] },
  { char: 'ホ', romaji: ['ho'] },
  { char: 'マ', romaji: ['ma'] }, { char: 'ミ', romaji: ['mi'] },
  { char: 'ム', romaji: ['mu'] }, { char: 'メ', romaji: ['me'] },
  { char: 'モ', romaji: ['mo'] },
  { char: 'ヤ', romaji: ['ya'] }, { char: 'ユ', romaji: ['yu'] },
  { char: 'ヨ', romaji: ['yo'] },
  { char: 'ラ', romaji: ['ra'] }, { char: 'リ', romaji: ['ri'] },
  { char: 'ル', romaji: ['ru'] }, { char: 'レ', romaji: ['re'] },
  { char: 'ロ', romaji: ['ro'] },
  { char: 'ワ', romaji: ['wa'] }, { char: 'ヲ', romaji: ['wo','o'] },
  { char: 'ン', romaji: ['n','nn'] },
  // Dakuten
  { char: 'ガ', romaji: ['ga'] }, { char: 'ギ', romaji: ['gi'] },
  { char: 'グ', romaji: ['gu'] }, { char: 'ゲ', romaji: ['ge'] },
  { char: 'ゴ', romaji: ['go'] },
  { char: 'ザ', romaji: ['za'] }, { char: 'ジ', romaji: ['ji','zi'] },
  { char: 'ズ', romaji: ['zu'] }, { char: 'ゼ', romaji: ['ze'] },
  { char: 'ゾ', romaji: ['zo'] },
  { char: 'ダ', romaji: ['da'] }, { char: 'ヂ', romaji: ['ji','di','zi'] },
  { char: 'ヅ', romaji: ['zu','du'] }, { char: 'デ', romaji: ['de'] },
  { char: 'ド', romaji: ['do'] },
  { char: 'バ', romaji: ['ba'] }, { char: 'ビ', romaji: ['bi'] },
  { char: 'ブ', romaji: ['bu'] }, { char: 'ベ', romaji: ['be'] },
  { char: 'ボ', romaji: ['bo'] },
  // Handakuten
  { char: 'パ', romaji: ['pa'] }, { char: 'ピ', romaji: ['pi'] },
  { char: 'プ', romaji: ['pu'] }, { char: 'ペ', romaji: ['pe'] },
  { char: 'ポ', romaji: ['po'] },
];

// ── Hiragana words ────────────────────────────────────────────
const HIRAGANA_WORDS = [
  { word:'ねこ',     romaji:['neko'],              meaning:'cat',            emoji:'🐱', sentence:'ねこがいます。',               sentenceEn:'There is a cat.'           },
  { word:'いぬ',     romaji:['inu'],               meaning:'dog',            emoji:'🐶', sentence:'いぬがすきです。',             sentenceEn:'I like dogs.'              },
  { word:'さかな',   romaji:['sakana'],            meaning:'fish',           emoji:'🐟', sentence:'さかなをたべます。',           sentenceEn:'I eat fish.'               },
  { word:'とり',     romaji:['tori'],              meaning:'bird',           emoji:'🐦', sentence:'とりがとんでいます。',         sentenceEn:'The bird is flying.'       },
  { word:'うさぎ',   romaji:['usagi'],             meaning:'rabbit',         emoji:'🐰', sentence:'うさぎはしろいです。',         sentenceEn:'The rabbit is white.'      },
  { word:'はな',     romaji:['hana'],              meaning:'flower',         emoji:'🌸', sentence:'はなはきれいです。',           sentenceEn:'The flower is beautiful.'  },
  { word:'き',       romaji:['ki'],                meaning:'tree',           emoji:'🌳', sentence:'きがおおきいです。',           sentenceEn:'The tree is big.'          },
  { word:'やま',     romaji:['yama'],              meaning:'mountain',       emoji:'🏔️', sentence:'やまにのぼります。',           sentenceEn:'I climb the mountain.'     },
  { word:'うみ',     romaji:['umi'],               meaning:'sea',            emoji:'🌊', sentence:'うみはあおいです。',           sentenceEn:'The sea is blue.'          },
  { word:'かわ',     romaji:['kawa'],              meaning:'river',          emoji:'🏞️', sentence:'かわでおよぎます。',           sentenceEn:'I swim in the river.'      },
  { word:'そら',     romaji:['sora'],              meaning:'sky',            emoji:'🌤️', sentence:'そらはあおいです。',           sentenceEn:'The sky is blue.'          },
  { word:'ほし',     romaji:['hoshi'],             meaning:'star',           emoji:'⭐', sentence:'ほしがきれいです。',           sentenceEn:'The stars are beautiful.'  },
  { word:'つき',     romaji:['tsuki','tuki'],      meaning:'moon',           emoji:'🌙', sentence:'つきがみえます。',             sentenceEn:'I can see the moon.'       },
  { word:'あめ',     romaji:['ame'],               meaning:'rain',           emoji:'🌧️', sentence:'あめがふっています。',         sentenceEn:'It is raining.'            },
  { word:'ゆき',     romaji:['yuki'],              meaning:'snow',           emoji:'❄️', sentence:'ゆきがふります。',             sentenceEn:'Snow falls.'               },
  { word:'かぜ',     romaji:['kaze'],              meaning:'wind',           emoji:'💨', sentence:'かぜがつよいです。',           sentenceEn:'The wind is strong.'       },
  { word:'みず',     romaji:['mizu'],              meaning:'water',          emoji:'💧', sentence:'みずをのみます。',             sentenceEn:'I drink water.'            },
  { word:'くも',     romaji:['kumo'],              meaning:'cloud',          emoji:'☁️', sentence:'くもがおおいです。',           sentenceEn:'There are many clouds.'    },
  { word:'いえ',     romaji:['ie'],                meaning:'house',          emoji:'🏠', sentence:'いえにかえります。',           sentenceEn:'I return home.'            },
  { word:'て',       romaji:['te'],                meaning:'hand',           emoji:'✋', sentence:'てをあらいます。',             sentenceEn:'I wash my hands.'          },
  { word:'あし',     romaji:['ashi'],              meaning:'foot / leg',     emoji:'🦶', sentence:'あしがいたいです。',           sentenceEn:'My foot hurts.'            },
  { word:'め',       romaji:['me'],                meaning:'eye',            emoji:'👁️', sentence:'めがいたいです。',             sentenceEn:'My eye hurts.'             },
  { word:'くち',     romaji:['kuchi'],             meaning:'mouth',          emoji:'👄', sentence:'くちをあけます。',             sentenceEn:'I open my mouth.'          },
  { word:'みみ',     romaji:['mimi'],              meaning:'ear',            emoji:'👂', sentence:'みみできこえます。',           sentenceEn:'I hear with my ears.'      },
  { word:'あたま',   romaji:['atama'],             meaning:'head',           emoji:'🧠', sentence:'あたまがいたいです。',         sentenceEn:'My head hurts.'            },
  { word:'こころ',   romaji:['kokoro'],            meaning:'heart / mind',   emoji:'💖', sentence:'こころがあたたかい。',         sentenceEn:'My heart is warm.'         },
  { word:'たべもの', romaji:['tabemono'],          meaning:'food',           emoji:'🍽️', sentence:'たべものがおいしい。',         sentenceEn:'The food is delicious.'    },
  { word:'のみもの', romaji:['nomimono'],          meaning:'drink',          emoji:'🥤', sentence:'のみものをください。',         sentenceEn:'Please give me a drink.'   },
  { word:'ごはん',   romaji:['gohan'],             meaning:'rice / meal',    emoji:'🍚', sentence:'ごはんをたべます。',           sentenceEn:'I eat rice.'               },
  { word:'みそ',     romaji:['miso'],              meaning:'miso',           emoji:'🫕', sentence:'みそしるがすきです。',         sentenceEn:'I like miso soup.'         },
  { word:'すし',     romaji:['sushi'],             meaning:'sushi',          emoji:'🍣', sentence:'すしはおいしいです。',         sentenceEn:'Sushi is delicious.'       },
  { word:'くるま',   romaji:['kuruma'],            meaning:'car',            emoji:'🚗', sentence:'くるまにのります。',           sentenceEn:'I ride in a car.'          },
  { word:'でんしゃ', romaji:['densha'],            meaning:'train',          emoji:'🚃', sentence:'でんしゃにのります。',         sentenceEn:'I ride the train.'         },
  { word:'みち',     romaji:['michi'],             meaning:'road / path',    emoji:'🛣️', sentence:'みちをあるきます。',           sentenceEn:'I walk along the road.'    },
  { word:'まち',     romaji:['machi'],             meaning:'town / city',    emoji:'🏙️', sentence:'まちがにぎやかです。',         sentenceEn:'The town is lively.'       },
  { word:'がっこう', romaji:['gakkou','gakko'],   meaning:'school',         emoji:'🏫', sentence:'がっこうにいきます。',         sentenceEn:'I go to school.'           },
  { word:'しごと',   romaji:['shigoto','sigoto'], meaning:'work / job',     emoji:'💼', sentence:'しごとがいそがしい。',         sentenceEn:'Work is busy.'             },
  { word:'ともだち', romaji:['tomodachi'],         meaning:'friend',         emoji:'🤝', sentence:'ともだちがいます。',           sentenceEn:'I have friends.'           },
  { word:'かぞく',   romaji:['kazoku'],            meaning:'family',         emoji:'👨‍👩‍👧', sentence:'かぞくがすきです。',           sentenceEn:'I love my family.'         },
  { word:'こども',   romaji:['kodomo'],            meaning:'child',          emoji:'👶', sentence:'こどもがあそびます。',         sentenceEn:'Children play.'            },
  { word:'せんせい', romaji:['sensei'],            meaning:'teacher',        emoji:'👩‍🏫', sentence:'せんせいはやさしい。',         sentenceEn:'The teacher is kind.'      },
  { word:'がくせい', romaji:['gakusei'],           meaning:'student',        emoji:'🎒', sentence:'がくせいがべんきょうします。', sentenceEn:'Students study.'           },
  { word:'きょう',   romaji:['kyou','kyo'],        meaning:'today',          emoji:'📅', sentence:'きょうはいいてんきです。',     sentenceEn:'Today is good weather.'    },
  { word:'あした',   romaji:['ashita'],            meaning:'tomorrow',       emoji:'🌅', sentence:'あしたはやすみです。',         sentenceEn:'Tomorrow is a holiday.'    },
  { word:'きのう',   romaji:['kinou','kino'],      meaning:'yesterday',      emoji:'📆', sentence:'きのうはたのしかった。',       sentenceEn:'Yesterday was fun.'        },
  { word:'おおきい', romaji:['ookii','oki'],       meaning:'big / large',    emoji:'🔵', sentence:'おおきいいぬです。',           sentenceEn:'It is a big dog.'          },
  { word:'ちいさい', romaji:['chiisai','chisai'],  meaning:'small / little', emoji:'🔹', sentence:'ちいさいねこです。',           sentenceEn:'It is a small cat.'        },
  { word:'あかい',   romaji:['akai'],              meaning:'red',            emoji:'🔴', sentence:'あかいはながさきます。',       sentenceEn:'Red flowers bloom.'        },
  { word:'あおい',   romaji:['aoi'],               meaning:'blue',           emoji:'🔵', sentence:'あおいそらです。',             sentenceEn:'It is a blue sky.'         },
  { word:'しろい',   romaji:['shiroi','siroi'],    meaning:'white',          emoji:'⬜', sentence:'しろいゆきです。',             sentenceEn:'It is white snow.'         },
  { word:'くろい',   romaji:['kuroi'],             meaning:'black',          emoji:'⬛', sentence:'くろいくもです。',             sentenceEn:'It is black clouds.'       },
  { word:'きいろい', romaji:['kiiroi'],            meaning:'yellow',         emoji:'🟡', sentence:'きいろいはなです。',           sentenceEn:'It is a yellow flower.'    },
  { word:'すき',     romaji:['suki'],              meaning:'like / love',    emoji:'❤️', sentence:'にほんごがすきです。',         sentenceEn:'I like Japanese.'          },
  { word:'たかい',   romaji:['takai'],             meaning:'high / expensive',emoji:'📈',sentence:'このやまはたかい。',           sentenceEn:'This mountain is high.'    },
  { word:'やすい',   romaji:['yasui'],             meaning:'cheap / easy',   emoji:'💰', sentence:'このりんごはやすい。',         sentenceEn:'This apple is cheap.'      },
  { word:'いま',     romaji:['ima'],               meaning:'now',            emoji:'⏰', sentence:'いまなんじですか？',           sentenceEn:'What time is it now?'      },
  { word:'まえ',     romaji:['mae'],               meaning:'front / before', emoji:'⬅️', sentence:'まえをみてください。',         sentenceEn:'Please look forward.'      },
  { word:'うしろ',   romaji:['ushiro'],            meaning:'behind / back',  emoji:'➡️', sentence:'うしろをむきます。',           sentenceEn:'I turn around.'            },
  { word:'みぎ',     romaji:['migi'],              meaning:'right',          emoji:'👉', sentence:'みぎにまがります。',           sentenceEn:'I turn right.'             },
  { word:'ひだり',   romaji:['hidari'],            meaning:'left',           emoji:'👈', sentence:'ひだりにまがります。',         sentenceEn:'I turn left.'              },
];

// ── Katakana words (loanwords) ────────────────────────────────
const KATAKANA_WORDS = [
  { word:'コーヒー',       romaji:['koohii','kohii','kohi'],        meaning:'coffee',            emoji:'☕', sentence:'コーヒーをのみます。',         sentenceEn:'I drink coffee.'           },
  { word:'テレビ',         romaji:['terebi'],                       meaning:'television',        emoji:'📺', sentence:'テレビをみます。',             sentenceEn:'I watch TV.'               },
  { word:'パン',           romaji:['pan'],                          meaning:'bread',             emoji:'🍞', sentence:'パンをたべます。',             sentenceEn:'I eat bread.'              },
  { word:'バス',           romaji:['basu'],                         meaning:'bus',               emoji:'🚌', sentence:'バスにのります。',             sentenceEn:'I ride the bus.'           },
  { word:'タクシー',       romaji:['takushii','takushi'],           meaning:'taxi',              emoji:'🚕', sentence:'タクシーをつかいます。',       sentenceEn:'I use a taxi.'             },
  { word:'ホテル',         romaji:['hoteru'],                       meaning:'hotel',             emoji:'🏨', sentence:'ホテルにとまります。',         sentenceEn:'I stay at a hotel.'        },
  { word:'レストラン',     romaji:['resutoran'],                    meaning:'restaurant',        emoji:'🍽️', sentence:'レストランでたべます。',       sentenceEn:'I eat at a restaurant.'    },
  { word:'ジュース',       romaji:['juusu','jusu'],                 meaning:'juice',             emoji:'🧃', sentence:'ジュースをのみます。',         sentenceEn:'I drink juice.'            },
  { word:'ビール',         romaji:['biiru','biru'],                 meaning:'beer',              emoji:'🍺', sentence:'ビールがすきです。',           sentenceEn:'I like beer.'              },
  { word:'ケーキ',         romaji:['keeki','keki'],                 meaning:'cake',              emoji:'🎂', sentence:'ケーキをたべます。',           sentenceEn:'I eat cake.'               },
  { word:'ピザ',           romaji:['piza','pizza'],                 meaning:'pizza',             emoji:'🍕', sentence:'ピザをちゅうもんします。',     sentenceEn:'I order pizza.'            },
  { word:'スポーツ',       romaji:['supootsu','supotsu'],           meaning:'sports',            emoji:'⚽', sentence:'スポーツがすきです。',         sentenceEn:'I like sports.'            },
  { word:'ゲーム',         romaji:['geemu','gemu'],                 meaning:'game',              emoji:'🎮', sentence:'ゲームをします。',             sentenceEn:'I play games.'             },
  { word:'カメラ',         romaji:['kamera'],                       meaning:'camera',            emoji:'📷', sentence:'カメラでしゃしんをとります。', sentenceEn:'I take photos with a camera.' },
  { word:'チョコレート',   romaji:['chokoreeto','chokoreto'],       meaning:'chocolate',         emoji:'🍫', sentence:'チョコレートがすきです。',     sentenceEn:'I like chocolate.'         },
  { word:'ミルク',         romaji:['miruku'],                       meaning:'milk',              emoji:'🥛', sentence:'ミルクをのみます。',           sentenceEn:'I drink milk.'             },
  { word:'バナナ',         romaji:['banana'],                       meaning:'banana',            emoji:'🍌', sentence:'バナナをたべます。',           sentenceEn:'I eat a banana.'           },
  { word:'オレンジ',       romaji:['orenji'],                       meaning:'orange',            emoji:'🍊', sentence:'オレンジがすきです。',         sentenceEn:'I like oranges.'           },
  { word:'トマト',         romaji:['tomato'],                       meaning:'tomato',            emoji:'🍅', sentence:'トマトがあかいです。',         sentenceEn:'Tomatoes are red.'         },
  { word:'サラダ',         romaji:['sarada'],                       meaning:'salad',             emoji:'🥗', sentence:'サラダをたべます。',           sentenceEn:'I eat salad.'              },
  { word:'スープ',         romaji:['suupu','supu'],                 meaning:'soup',              emoji:'🍲', sentence:'スープがあつい。',             sentenceEn:'The soup is hot.'          },
  { word:'パスタ',         romaji:['pasuta'],                       meaning:'pasta',             emoji:'🍝', sentence:'パスタをつくります。',         sentenceEn:'I make pasta.'             },
  { word:'ハンバーガー',   romaji:['hanbaagaa','hanbaaga'],         meaning:'hamburger',         emoji:'🍔', sentence:'ハンバーガーをたべます。',     sentenceEn:'I eat a hamburger.'        },
  { word:'アイス',         romaji:['aisu'],                         meaning:'ice cream',         emoji:'🍦', sentence:'アイスがたべたい。',           sentenceEn:'I want to eat ice cream.'  },
  { word:'コーラ',         romaji:['koora','kora'],                 meaning:'cola',              emoji:'🥤', sentence:'コーラをのみます。',           sentenceEn:'I drink cola.'             },
  { word:'ワイン',         romaji:['wain'],                         meaning:'wine',              emoji:'🍷', sentence:'ワインをのみます。',           sentenceEn:'I drink wine.'             },
  { word:'チーズ',         romaji:['chiizu','chizu'],               meaning:'cheese',            emoji:'🧀', sentence:'チーズがすきです。',           sentenceEn:'I like cheese.'            },
  { word:'バター',         romaji:['bataa','bata'],                 meaning:'butter',            emoji:'🧈', sentence:'バターをつかいます。',         sentenceEn:'I use butter.'             },
  { word:'サンドイッチ',   romaji:['sandoicchi','sandoitchi'],      meaning:'sandwich',          emoji:'🥪', sentence:'サンドイッチをつくります。',   sentenceEn:'I make a sandwich.'        },
  { word:'ヨーグルト',     romaji:['yooguruto','yoguruto'],         meaning:'yogurt',            emoji:'🥣', sentence:'ヨーグルトをたべます。',       sentenceEn:'I eat yogurt.'             },
  { word:'ポテト',         romaji:['poteto'],                       meaning:'potato',            emoji:'🥔', sentence:'ポテトをたべます。',           sentenceEn:'I eat potatoes.'           },
  { word:'カレー',         romaji:['karee','kare'],                 meaning:'curry',             emoji:'🍛', sentence:'カレーがすきです。',           sentenceEn:'I like curry.'             },
  { word:'スマホ',         romaji:['sumaho'],                       meaning:'smartphone',        emoji:'📱', sentence:'スマホをつかいます。',         sentenceEn:'I use a smartphone.'       },
  { word:'タブレット',     romaji:['taburetto'],                    meaning:'tablet',            emoji:'📲', sentence:'タブレットでみます。',         sentenceEn:'I watch on a tablet.'      },
  { word:'パソコン',       romaji:['pasokon'],                      meaning:'personal computer', emoji:'💻', sentence:'パソコンでしごとをします。',   sentenceEn:'I work on a PC.'           },
  { word:'ベッド',         romaji:['beddo','bedo'],                 meaning:'bed',               emoji:'🛏️', sentence:'ベッドでねます。',             sentenceEn:'I sleep in bed.'           },
  { word:'ソファ',         romaji:['sofa'],                         meaning:'sofa',              emoji:'🛋️', sentence:'ソファにすわります。',         sentenceEn:'I sit on the sofa.'        },
  { word:'テーブル',       romaji:['teebu','teeburu','teburu'],     meaning:'table',             emoji:'🪑', sentence:'テーブルにおきます。',         sentenceEn:'I put it on the table.'    },
  { word:'ドア',           romaji:['doa'],                          meaning:'door',              emoji:'🚪', sentence:'ドアをあけます。',             sentenceEn:'I open the door.'          },
  { word:'インターネット', romaji:['intaanetto','intanetto'],       meaning:'internet',          emoji:'🌐', sentence:'インターネットをつかいます。', sentenceEn:'I use the internet.'       },
  { word:'エレベーター',   romaji:['erebeetaa','erebeta'],          meaning:'elevator',          emoji:'🛗', sentence:'エレベーターにのります。',     sentenceEn:'I ride the elevator.'      },
  { word:'スーパー',       romaji:['suupaa','supa'],                meaning:'supermarket',       emoji:'🏪', sentence:'スーパーでかいます。',         sentenceEn:'I buy at the supermarket.' },
  { word:'デパート',       romaji:['depaato','depato'],             meaning:'department store',  emoji:'🏬', sentence:'デパートにいきます。',         sentenceEn:'I go to the department store.' },
  { word:'アパート',       romaji:['apaato','apato'],               meaning:'apartment',         emoji:'🏢', sentence:'アパートにすんでいます。',     sentenceEn:'I live in an apartment.'   },
  { word:'マンゴー',       romaji:['mangoo','mango'],               meaning:'mango',             emoji:'🥭', sentence:'マンゴーはあまい。',           sentenceEn:'Mango is sweet.'           },
  { word:'アップル',       romaji:['appuru'],                       meaning:'apple',             emoji:'🍎', sentence:'アップルをたべます。',         sentenceEn:'I eat an apple.'           },
  { word:'ギター',         romaji:['gitaa','gita'],                 meaning:'guitar',            emoji:'🎸', sentence:'ギターをひきます。',           sentenceEn:'I play guitar.'            },
  { word:'ピアノ',         romaji:['piano'],                        meaning:'piano',             emoji:'🎹', sentence:'ピアノをならいます。',         sentenceEn:'I learn piano.'            },
  { word:'ダンス',         romaji:['dansu'],                        meaning:'dance',             emoji:'💃', sentence:'ダンスをおどります。',         sentenceEn:'I dance.'                  },
  { word:'スキー',         romaji:['sukii','suki'],                 meaning:'skiing',            emoji:'🎿', sentence:'スキーをします。',             sentenceEn:'I go skiing.'              },
  { word:'プール',         romaji:['puuru','puru'],                 meaning:'pool',              emoji:'🏊', sentence:'プールでおよぎます。',         sentenceEn:'I swim in the pool.'       },
  { word:'パーティー',     romaji:['paatii','pati'],                meaning:'party',             emoji:'🎉', sentence:'パーティーをします。',         sentenceEn:'I have a party.'           },
  { word:'ニュース',       romaji:['nyuusu','nyusu'],               meaning:'news',              emoji:'📰', sentence:'ニュースをみます。',           sentenceEn:'I watch the news.'         },
  { word:'ラジオ',         romaji:['rajio'],                        meaning:'radio',             emoji:'📻', sentence:'ラジオをききます。',           sentenceEn:'I listen to the radio.'    },
  { word:'ミュージック',   romaji:['myuujikku','myujikku'],         meaning:'music',             emoji:'🎵', sentence:'ミュージックがすきです。',     sentenceEn:'I like music.'             },
  { word:'チケット',       romaji:['chiketto'],                     meaning:'ticket',            emoji:'🎟️', sentence:'チケットをかいます。',         sentenceEn:'I buy a ticket.'           },
  { word:'ネクタイ',       romaji:['nekutai'],                      meaning:'necktie',           emoji:'👔', sentence:'ネクタイをしめます。',         sentenceEn:'I tie a necktie.'          },
  { word:'シャツ',         romaji:['shatsu'],                       meaning:'shirt',             emoji:'👕', sentence:'シャツをきます。',             sentenceEn:'I wear a shirt.'           },
  { word:'ズボン',         romaji:['zubon'],                        meaning:'trousers',          emoji:'👖', sentence:'ズボンをはきます。',           sentenceEn:'I wear trousers.'          },
];

// ── Reference chart grids ─────────────────────────────────────
const CHART_GRIDS = {
  hiragana: {
    basic: [
      ['あ','い','う','え','お'],
      ['か','き','く','け','こ'],
      ['さ','し','す','せ','そ'],
      ['た','ち','つ','て','と'],
      ['な','に','ぬ','ね','の'],
      ['は','ひ','ふ','へ','ほ'],
      ['ま','み','む','め','も'],
      ['や','','ゆ','','よ'],
      ['ら','り','る','れ','ろ'],
      ['わ','','','','を'],
      ['ん','','','',''],
    ],
    dakuten: [
      ['が','ぎ','ぐ','げ','ご'],
      ['ざ','じ','ず','ぜ','ぞ'],
      ['だ','ぢ','づ','で','ど'],
      ['ば','び','ぶ','べ','ぼ'],
    ],
    handakuten: [
      ['ぱ','ぴ','ぷ','ぺ','ぽ'],
    ],
  },
  katakana: {
    basic: [
      ['ア','イ','ウ','エ','オ'],
      ['カ','キ','ク','ケ','コ'],
      ['サ','シ','ス','セ','ソ'],
      ['タ','チ','ツ','テ','ト'],
      ['ナ','ニ','ヌ','ネ','ノ'],
      ['ハ','ヒ','フ','ヘ','ホ'],
      ['マ','ミ','ム','メ','モ'],
      ['ヤ','','ユ','','ヨ'],
      ['ラ','リ','ル','レ','ロ'],
      ['ワ','','','','ヲ'],
      ['ン','','','',''],
    ],
    dakuten: [
      ['ガ','ギ','グ','ゲ','ゴ'],
      ['ザ','ジ','ズ','ゼ','ゾ'],
      ['ダ','ヂ','ヅ','デ','ド'],
      ['バ','ビ','ブ','ベ','ボ'],
    ],
    handakuten: [
      ['パ','ピ','プ','ペ','ポ'],
    ],
  },
};

// ── Alphabet row levels ───────────────────────────────────────
const ALPHA_LEVELS = {
  hiragana: [
    { label: 'Vowels (あ行)',      chars: ['あ','い','う','え','お'] },
    { label: 'K sound (か行)',     chars: ['か','き','く','け','こ'] },
    { label: 'S sound (さ行)',     chars: ['さ','し','す','せ','そ'] },
    { label: 'T sound (た行)',     chars: ['た','ち','つ','て','と'] },
    { label: 'N sound (な行)',     chars: ['な','に','ぬ','ね','の'] },
    { label: 'H sound (は行)',     chars: ['は','ひ','ふ','へ','ほ'] },
    { label: 'M sound (ま行)',     chars: ['ま','み','む','め','も'] },
    { label: 'Y sound (や行)',     chars: ['や','ゆ','よ'] },
    { label: 'R sound (ら行)',     chars: ['ら','り','る','れ','ろ'] },
    { label: 'W/N (わ行)',         chars: ['わ','を','ん'] },
    { label: 'G sound (が行)',     chars: ['が','ぎ','ぐ','げ','ご'] },
    { label: 'Z/J sound (ざ行)',   chars: ['ざ','じ','ず','ぜ','ぞ'] },
    { label: 'D sound (だ行)',     chars: ['だ','ぢ','づ','で','ど'] },
    { label: 'B sound (ば行)',     chars: ['ば','び','ぶ','べ','ぼ'] },
    { label: 'P sound (ぱ行)',     chars: ['ぱ','ぴ','ぷ','ぺ','ぽ'] },
    { label: 'All Basic',         chars: ['あ','い','う','え','お','か','き','く','け','こ','さ','し','す','せ','そ','た','ち','つ','て','と','な','に','ぬ','ね','の','は','ひ','ふ','へ','ほ','ま','み','む','め','も','や','ゆ','よ','ら','り','る','れ','ろ','わ','を','ん'] },
    { label: 'All Dakuten',       chars: ['が','ぎ','ぐ','げ','ご','ざ','じ','ず','ぜ','ぞ','だ','ぢ','づ','で','ど','ば','び','ぶ','べ','ぼ','ぱ','ぴ','ぷ','ぺ','ぽ'] },
    { label: 'Full Deck',         chars: null },
  ],
  katakana: [
    { label: 'Vowels (ア行)',      chars: ['ア','イ','ウ','エ','オ'] },
    { label: 'K sound (カ行)',     chars: ['カ','キ','ク','ケ','コ'] },
    { label: 'S sound (サ行)',     chars: ['サ','シ','ス','セ','ソ'] },
    { label: 'T sound (タ行)',     chars: ['タ','チ','ツ','テ','ト'] },
    { label: 'N sound (ナ行)',     chars: ['ナ','ニ','ヌ','ネ','ノ'] },
    { label: 'H sound (ハ行)',     chars: ['ハ','ヒ','フ','ヘ','ホ'] },
    { label: 'M sound (マ行)',     chars: ['マ','ミ','ム','メ','モ'] },
    { label: 'Y sound (ヤ行)',     chars: ['ヤ','ユ','ヨ'] },
    { label: 'R sound (ラ行)',     chars: ['ラ','リ','ル','レ','ロ'] },
    { label: 'W/N (ワ行)',         chars: ['ワ','ヲ','ン'] },
    { label: 'G sound (ガ行)',     chars: ['ガ','ギ','グ','ゲ','ゴ'] },
    { label: 'Z/J sound (ザ行)',   chars: ['ザ','ジ','ズ','ゼ','ゾ'] },
    { label: 'D sound (ダ行)',     chars: ['ダ','ヂ','ヅ','デ','ド'] },
    { label: 'B sound (バ行)',     chars: ['バ','ビ','ブ','ベ','ボ'] },
    { label: 'P sound (パ行)',     chars: ['パ','ピ','プ','ペ','ポ'] },
    { label: 'All Basic',         chars: ['ア','イ','ウ','エ','オ','カ','キ','ク','ケ','コ','サ','シ','ス','セ','ソ','タ','チ','ツ','テ','ト','ナ','ニ','ヌ','ネ','ノ','ハ','ヒ','フ','ヘ','ホ','マ','ミ','ム','メ','モ','ヤ','ユ','ヨ','ラ','リ','ル','レ','ロ','ワ','ヲ','ン'] },
    { label: 'All Dakuten',       chars: ['ガ','ギ','グ','ゲ','ゴ','ザ','ジ','ズ','ゼ','ゾ','ダ','ヂ','ヅ','デ','ド','バ','ビ','ブ','ベ','ボ','パ','ピ','プ','ペ','ポ'] },
    { label: 'Full Deck',         chars: null },
  ],
};

// ── Romaji lookup map ─────────────────────────────────────────
const ROMAJI_MAP = {};
[...HIRAGANA, ...KATAKANA].forEach(({ char, romaji }) => {
  ROMAJI_MAP[char] = romaji[0];
});
